/** @type {import('tailwindcss').Config} */
export default {
  content: ["./index.html", "./src/**/*.{vue,js,ts,jsx,tsx}"],
  safelist: [
    // 기본 팀 색상 (폰트 및 배경)
    "text-Landers",
    "bg-Landers",
    "text-Twins",
    "bg-Twins",
    "text-Heros",
    "bg-Heros",
    "text-Dinos",
    "bg-Dinos",
    "text-Tigers",
    "bg-Tigers",
    "text-Bears",
    "bg-Bears",
    "text-Giants",
    "bg-Giants",
    "text-Lions",
    "bg-Lions",
    "text-Eagles",
    "bg-Eagles",
    "text-Wiz",
    "bg-Wiz",

    // 10% 투명도 색상
    "text-Landers_opa10",
    "bg-Landers_opa10",
    "text-Twins_opa10",
    "bg-Twins_opa10",
    "text-Heros_opa10",
    "bg-Heros_opa10",
    "text-Dinos_opa10",
    "bg-Dinos_opa10",
    "text-Tigers_opa10",
    "bg-Tigers_opa10",
    "text-Bears_opa10",
    "bg-Bears_opa10",
    "text-Giants_opa10",
    "bg-Giants_opa10",
    "text-Lions_opa10",
    "bg-Lions_opa10",
    "text-Eagles_opa10",
    "bg-Eagles_opa10",
    "text-Wiz_opa10",
    "bg-Wiz_opa10",

    // 30% 투명도 색상
    "text-Landers_opa30",
    "bg-Landers_opa30",
    "text-Twins_opa30",
    "bg-Twins_opa30",
    "text-Heros_opa30",
    "bg-Heros_opa30",
    "text-Dinos_opa30",
    "bg-Dinos_opa30",
    "text-Tigers_opa30",
    "bg-Tigers_opa30",
    "text-Bears_opa30",
    "bg-Bears_opa30",
    "text-Giants_opa30",
    "bg-Giants_opa30",
    "text-Lions_opa30",
    "bg-Lions_opa30",
    "text-Eagles_opa30",
    "bg-Eagles_opa30",
    "text-Wiz_opa30",
    "bg-Wiz_opa30",

    // 호버 배경색
    "hover:bg-Landers_opa10",
    "hover:bg-Twins_opa10",
    "hover:bg-Heros_opa10",
    "hover:bg-Dinos_opa10",
    "hover:bg-Tigers_opa10",
    "hover:bg-Bears_opa10",
    "hover:bg-Giants_opa10",
    "hover:bg-Lions_opa10",
    "hover:bg-Eagles_opa10",
    "hover:bg-Wiz_opa10",
    "hover:bg-Landers_opa30",
    "hover:bg-Twins_opa30",
    "hover:bg-Heros_opa30",
    "hover:bg-Dinos_opa30",
    "hover:bg-Tigers_opa30",
    "hover:bg-Bears_opa30",
    "hover:bg-Giants_opa30",
    "hover:bg-Lions_opa30",
    "hover:bg-Eagles_opa30",
    "hover:bg-Wiz_opa30",

    // 호버 텍스트
    "hover:text-Landers",
    "hover:text-Twins",
    "hover:text-Heros",
    "hover:text-Dinos",
    "hover:text-Tigers",
    "hover:text-Bears",
    "hover:text-Giants",
    "hover:text-Lions",
    "hover:text-Eagles",
    "hover:text-Wiz",
    "hover:text-black01",
  ],
  theme: {
    extend: {
      colors: {
        white01: "#FAFAFA",
        white02: "#EEEEEE",
        black01: "#0A0A0A",
        black02: "#1E1E1E",
        gray01: "#B1B1B1",
        gray02: "#919191",
        gray03: "#515151",
        progressing: "#34C300",
        Done: "#F50000",
        gameGreen: "#0BF89F",
        Heros: "#570514",
        Bears: "#1A1748",
        Giants: "#041E42",
        Lions: "#074CA1",
        Eagles: "#F04E00",
        Tigers: "#EA0029",
        Twins: "#C30452",
        Landers: "#CE0E2D",
        Dinos: "#315288",
        Wiz: "#EB1C24",
        // 투명도 10%
        Heros_opa10: "#EEE6E7",
        Bears_opa10: "#E8E8ED",
        Giants_opa10: "#E6E8EC",
        Lions_opa10: "#E6EDF6",
        Eagles_opa10: "#FDEDE5",
        Tigers_opa10: "#FDE5EA",
        Twins_opa10: "#F9E6EE",
        Landers_opa10: "#FAE7EA",
        Dinos_opa10: "#EAEEF3",
        Wiz_opa10: "#FDE8E9",

        // 투명도 30%
        Heros_opa30: "#CDB4B8",
        Bears_opa30: "#BAB9C8",
        Giants_opa30: "#B4BBC6",
        Lions_opa30: "#B5C9E3",
        Eagles_opa30: "#FBCAB2",
        Tigers_opa30: "#F9B2BF",
        Twins_opa30: "#EDB4CB",
        Landers_opa30: "#F0B7C0",
        Dinos_opa30: "#C1CBDB",
        Wiz_opa30: "#F9BBBD",
      },
      fontFamily: {
        sigmar: ["Sigmar", "cursive"], // Sigmar 폰트 추가 -> tailwind에서 font-sigmar로 사용
        Galmuri11: ["Galmuri11", "sans-serif"],
      },
    },
  },
  plugins: [
    require("tailwind-scrollbar-hide"),
    require("@tailwindcss/typography"),
  ],
};
