import {
  django_logo,
  express_logo,
  firebase_logo,
  git_logo,
  go_logo,
  graphql_logo,
  java_logo,
  jest_logo,
  mongodb_logo,
  mysql_logo,
  nestjs_logo,
  nodejs_logo,
  php_logo,
  python_logo,
  spring_logo,
} from '@/assets/images/skills';

export const BACKEND_SKILLS = [
  { name: 'Git', image: git_logo },
  { name: 'Java', image: java_logo },
  { name: 'Python', image: python_logo },
  { name: 'Go', image: go_logo },
  { name: 'Spring', image: spring_logo },
  { name: 'Express', image: express_logo },
  { name: 'Django', image: django_logo },
  { name: 'Node.js', image: nodejs_logo },
  { name: 'Nest.js', image: nestjs_logo },
  { name: 'Jest', image: jest_logo },
  { name: 'Firebase', image: firebase_logo },
  { name: 'GraphQL', image: graphql_logo },
  { name: 'PHP', image: php_logo },
  { name: 'MongoDB', image: mongodb_logo },
  { name: 'MySQL', image: mysql_logo },
];
